"""Add passport column to workers

Revision ID: 1621033cdd11
Revises: b58c6e654c72
Create Date: 2025-12-01 21:29:22.677761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1621033cdd11'
down_revision = 'b58c6e654c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
