"""Add time_in, time_out, notes to attendance

Revision ID: 1b8479e1791c
Revises: 2a7e44fd4cd9
Create Date: 2026-05-18 04:29:30.802264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8479e1791c'
down_revision = '2a7e44fd4cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_in', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('time_out', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=100), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_unique_constraint('_worker_date_uc', ['worker_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('_worker_date_uc', type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('time_out')
        batch_op.drop_column('time_in')

    # ### end Alembic commands ###
