"""Add worker_code field

Revision ID: 1d634fba5691
Revises: 2aef9d8ae63b
Create Date: 2025-07-27 14:47:04.424488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d634fba5691'
down_revision = '2aef9d8ae63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_code', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint("uq_worker_code", ['worker_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('worker_code')

    # ### end Alembic commands ###
