"""add email_logs

Revision ID: 2168a5a92b37
Revises: 8a8b970123e9
Create Date: 2026-05-05 16:56:05.659518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2168a5a92b37'
down_revision = '8a8b970123e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('driver', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('gross', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tare', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('net', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('records_pkey'))
    )
    op.drop_table('email_logs')
    # ### end Alembic commands ###
