"""Upgrade salary and worker models for monthly payroll

Revision ID: 2a7e44fd4cd9
Revises: 03e592645142
Create Date: 2026-05-18 03:22:39.490287

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2a7e44fd4cd9'
down_revision = '03e592645142'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('worker_name', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    # Fix for salary table: add month as nullable, backfill, then make NOT NULL
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('deductions', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('gross_salary', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('net_salary', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), nullable=False, server_default='false'))

    # Backfill month for existing rows
    op.execute("UPDATE salary SET month = to_char(now(), 'YYYY-MM') WHERE month IS NULL")
    
    # Now make month NOT NULL and add constraints
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.alter_column('month', nullable=False)
        batch_op.create_index('ix_salary_month', ['month'], unique=False)
        batch_op.create_unique_constraint('uq_worker_month_salary', ['worker_id', 'month'])

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_rate', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))
        batch_op.alter_column('worker_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.alter_column('worker_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('department')
        batch_op.drop_column('daily_rate')

    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.drop_constraint('uq_worker_month_salary', type_='unique')
        batch_op.drop_index('ix_salary_month')
        batch_op.drop_column('is_processed')
        batch_op.drop_column('net_salary')
        batch_op.drop_column('gross_salary')
        batch_op.drop_column('deductions')
        batch_op.drop_column('month')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    op.drop_table('payroll_lock')
    # ### end Alembic commands ###