"""Add passport column

Revision ID: 388d5af514d2
Revises: 1621033cdd11
Create Date: 2025-12-03 20:45:24.973782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388d5af514d2'
down_revision = '1621033cdd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('passport')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
