"""added  updated_at  to worker

Revision ID: 3934e94806a0
Revises: d4725c0ede7b
Create Date: 2026-05-13 15:38:05.220133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3934e94806a0'
down_revision = 'd4725c0ede7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_worker_id'), ['worker_id'], unique=False)

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('email_logs_worker_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_index(batch_op.f('ix_salary_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_worker_id'), ['worker_id'], unique=False)

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_worker_id'))
        batch_op.drop_index(batch_op.f('ix_salary_payment_date'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('email_logs_worker_id_fkey'), 'workers', ['worker_id'], ['id'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_worker_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_date'))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
