"""rebuild

Revision ID: 42fd077ae048
Revises: 
Create Date: 2026-04-25 21:14:23.756386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42fd077ae048'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - FIXED ###

    op.drop_table('playing_with_neon')
    op.drop_table('records')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column(
            'date',
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.Date(),
            existing_nullable=False
        )

    with op.batch_alter_table('workers', schema=None) as batch_op:
        # ✅ FIX: safe default added
        batch_op.add_column(
            sa.Column(
                'is_active',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('true')
            )
        )

        batch_op.add_column(
            sa.Column(
                'deactivation_reason',
                sa.String(length=255),
                nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - FIXED ###

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('deactivation_reason')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column(
            'date',
            existing_type=sa.Date(),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False
        )

    op.create_table(
        'records',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('vehicle', sa.VARCHAR(length=100), nullable=False),
        sa.Column('material', sa.VARCHAR(length=100), nullable=False),
        sa.Column('supplier', sa.VARCHAR(length=100)),
        sa.Column('driver', sa.VARCHAR(length=100)),
        sa.Column('gross', sa.DOUBLE_PRECISION()),
        sa.Column('tare', sa.DOUBLE_PRECISION()),
        sa.Column('net', sa.DOUBLE_PRECISION()),
        sa.Column('created_at', postgresql.TIMESTAMP()),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'playing_with_neon',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.TEXT(), nullable=False),
        sa.Column('value', sa.REAL()),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###