"""fix material_transactions model

Revision ID: 51f1834f42cf
Revises: c82a04583699
Create Date: 2026-06-12 12:25:12.151698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f1834f42cf'
down_revision = 'c82a04583699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_by_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verified_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('recorded_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('edited_at')
        batch_op.drop_column('is_edited')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by_id')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('date_created')
        batch_op.drop_column('recorded_by_name')

    # ### end Alembic commands ###
