"""Add passport column to workers table

Revision ID: 526b21fa57ab
Revises: 6b175a04e239
Create Date: 2025-12-01 05:20:57.843270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526b21fa57ab'
down_revision = '6b175a04e239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
