"""Updated salary model

Revision ID: 58a4d88e41f3
Revises: 3dfe74749a72
Create Date: 2025-08-08 16:44:01.559721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a4d88e41f3'
down_revision = '3dfe74749a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
