"""Add passport column to workers

Revision ID: 6b175a04e239
Revises: af2942d7ee13
Create Date: 2025-12-01 05:20:43.852291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b175a04e239'
down_revision = 'af2942d7ee13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('kilograms',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('number_of_bags')

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('passport')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_bags', sa.INTEGER(), nullable=True))
        batch_op.alter_column('kilograms',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
