"""Make amount_of_salary float, add bank_account_name to Salary

Revision ID: 81d00c0a9991
Revises: a4aa0cc2bcd4
Create Date: 2025-09-27 19:58:26.360266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d00c0a9991'
down_revision = 'a4aa0cc2bcd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.alter_column('amount_of_salary',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.alter_column('amount_of_salary',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.drop_column('bank_account_name')

    # ### end Alembic commands ###
