"""add worker status fields

Revision ID: 8a8b970123e9
Revises: 42fd077ae048
Create Date: 2026-04-25 23:06:08.864743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8b970123e9'
down_revision = '42fd077ae048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('status_letter', sa.Text(), nullable=True))
        batch_op.drop_column('deactivation_reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivation_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('status_letter')
        batch_op.drop_column('status_type')
        batch_op.drop_column('status_date')
        batch_op.drop_column('status_reason')

    # ### end Alembic commands ###
