"""Add passport column to workers

Revision ID: b58c6e654c72
Revises: ddcaa012d411
Create Date: 2025-12-01 21:17:53.280835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58c6e654c72'
down_revision = 'ddcaa012d411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
