"""Add amount_of_salary to Worker

Revision ID: b71bc728b5cb
Revises: 81d00c0a9991
Create Date: 2025-09-27 20:07:24.090442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71bc728b5cb'
down_revision = '81d00c0a9991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
