"""empty message

Revision ID: c82a04583699
Revises: 1b8479e1791c
Create Date: 2026-06-12 10:50:28.133740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c82a04583699'
down_revision = '1b8479e1791c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('client_supplier', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('recorded_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_transactions_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_transactions_transaction_date'), ['transaction_date'], unique=False)

    op.drop_table('records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('driver', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('gross', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tare', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('net', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('records_pkey'))
    )
    with op.batch_alter_table('material_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_material_transactions_material_id'))

    op.drop_table('material_transactions')
    op.drop_table('materials')
    # ### end Alembic commands ###
