"""fix  cascade delete

Revision ID: d4725c0ede7b
Revises: 5556f40fb209
Create Date: 2026-05-13 11:16:37.822824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4725c0ede7b'
down_revision = '5556f40fb209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_constraint(batch_op.f('attendance_worker_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_constraint(batch_op.f('salary_worker_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('salary_worker_id_fkey'), 'workers', ['worker_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_worker_id_fkey'), 'workers', ['worker_id'], ['id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
