"""initial clean

Revision ID: dd781f8731f7
Revises: 
Create Date: 2026-05-12 17:53:07.711125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd781f8731f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warning_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_action_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_action_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('last_action_date')
        batch_op.drop_column('last_action_by')
        batch_op.drop_column('warning_count')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')

    op.create_table('records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('driver', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('gross', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tare', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('net', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('records_pkey'))
    )
    # ### end Alembic commands ###
