"""Add passport column

Revision ID: ddcaa012d411
Revises: 526b21fa57ab
Create Date: 2025-12-01 20:34:08.470362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcaa012d411'
down_revision = '526b21fa57ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
