"""Initial migration

Revision ID: eb67d3846d2d
Revises: 
Create Date: 2026-04-04 12:24:00.527180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb67d3846d2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=150), nullable=True),
        sa.Column('email', sa.String(length=150), nullable=True),
        sa.Column('items', sa.String(length=50), nullable=True),
        sa.Column('kilograms', sa.Integer(), nullable=True),
        sa.Column('unit_price', sa.Float(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.Column('date_needed', sa.DateTime(), nullable=True),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),  # important column
        sa.Column('driver_name', sa.String(length=100), nullable=True),
        sa.Column('vehicle_plate_number', sa.String(length=50), nullable=True),
        sa.Column('bank_name', sa.String(length=100), nullable=True),
        sa.Column('account_number', sa.String(length=50), nullable=True),
        sa.Column('account_bank_name', sa.String(length=200), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('phone_number', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'workers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('worker_code', sa.String(length=10), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('phone_number', sa.String(length=20), nullable=False),
        sa.Column('date_of_birth', sa.Date(), nullable=False),
        sa.Column('gender', sa.String(length=10), nullable=False),
        sa.Column('qualifications', sa.String(length=100), nullable=False),
        sa.Column('position', sa.String(length=100), nullable=False),
        sa.Column('national_id', sa.String(length=50), nullable=False),
        sa.Column('nationality', sa.String(length=50), nullable=False),
        sa.Column('home_address', sa.String(length=200), nullable=False),
        sa.Column('ethnic_group', sa.String(length=50), nullable=False),
        sa.Column('place_of_residence', sa.String(length=100), nullable=False),
        sa.Column('disability', sa.String(length=100), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('date_of_employment', sa.Date(), nullable=False),
        sa.Column('amount_of_salary', sa.Float(), nullable=False),
        sa.Column('bank_name', sa.String(length=100), nullable=True),
        sa.Column('bank_account', sa.String(length=50), nullable=True),
        sa.Column('bank_account_name', sa.String(length=100), nullable=False),
        sa.Column('guarantor', sa.String(length=100), nullable=False),
        sa.Column('passport', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('worker_code')
    )

    op.create_table(
        'attendance',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('worker_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(['worker_id'], ['workers.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'salary',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('worker_id', sa.Integer(), nullable=False),
        sa.Column('total_days_present', sa.Integer(), nullable=False),
        sa.Column('daily_rate', sa.Float(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('bank_name', sa.String(length=100), nullable=True),
        sa.Column('bank_account', sa.String(length=50), nullable=True),
        sa.Column('bank_account_name', sa.String(length=100), nullable=True),
        sa.Column('payment_date', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['worker_id'], ['workers.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary')
    op.drop_table('attendance')
    op.drop_table('workers')
    op.drop_table('orders')
    # ### end Alembic commands ###